# Generated by Django 3.1.7 on 2021-03-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='This tweet is empty')),
                ('image', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='noUser', max_length=15, primary_key=True, serialize=False)),
                ('displayName', models.CharField(default='', max_length=140)),
                ('avatar', models.TextField(default='')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
