# Generated by Django 3.1.7 on 2021-03-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(default='noUser', on_delete=django.db.models.deletion.CASCADE, to='twitter_clone_backend.user'),
        ),
    ]
