# Generated by Django 3.1.7 on 2021-03-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0002_tweet_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='poster',
        ),
    ]
