# Generated by Django 3.1.7 on 2021-03-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0003_auto_20210312_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('name', models.CharField(default='anon', max_length=140, primary_key=True, serialize=False)),
                ('following', models.ManyToManyField(to='twitter_clone_backend.Poster')),
            ],
        ),
    ]
