# Generated by Django 3.1.7 on 2021-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0005_auto_20210312_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='avatar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
