# Generated by Django 3.1.7 on 2021-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0006_auto_20210314_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('name', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='', max_length=2400)),
            ],
        ),
    ]
