# Generated by Django 3.1.7 on 2021-03-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0007_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='explanation',
            field=models.ForeignKey(blank=True, default='default', on_delete=django.db.models.deletion.CASCADE, to='twitter_clone_backend.explanation'),
        ),
    ]
