# Generated by Django 3.1.7 on 2021-05-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0009_auto_20210326_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter_clone_backend.article'),
        ),
    ]
