# Generated by Django 3.1.7 on 2021-05-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0010_auto_20210508_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
