# Generated by Django 3.1.7 on 2021-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0011_auto_20210508_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.TextField(default='article', max_length=50),
        ),
    ]
