# Generated by Django 3.1.7 on 2021-05-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_backend', '0012_article_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_clone_backend.article'),
        ),
    ]
